### ISSUE TITLE
MicrosoftOpenXR Plugin for Unreal Holographic Streaming Crash in Packaged Build

### ISSUE THREAD

**Issue by gvindiol** [microsoft/OpenXR-MixedReality#113]
Hello, I'm seeking help with getting an Unreal Project to behave better with Holographic Streaming.
There is ton's of different behavior occurring and I've just kind of concluded that functionality is broken for packaged UE5.0+ applications although it works in-editor VR preview.
This wasn't a problem until we upgrade from UE 4.27.2 to 5.0.0-5.0.3

Windows Mixed Reality Plugin works for a packaged game to use holographic streaming.
MicrosoftOpenXR Plugin does not work for a packaged game to use holographic streaming.

`LogHMD: Error: Failed to create all visibility mask meshes for device/views. Abandoning visibility mask.`

`Assertion failed: PipelineState.bXrFrameStateUpdated`

Please see:
https://forums.unrealengine.com/t/openxr-with-msft-remoting-crash-in-ue5-0-3/609163/3
https://github.com/microsoft/Microsoft-OpenXR-Unreal/issues/79
https://github.com/microsoft/Microsoft-OpenXR-Unreal/issues/82

**Comment by mbucchia-msft** [comment]
We forwarded this request to Jackson and it looks like he replied on your other issues filed in Microsoft-OpenXR-Unreal since.

Closing.
