### ISSUE TITLE
OpenXR & Radeon 7900XTX & iRacing

### ISSUE THREAD

**Issue by indus3a** [microsoft/OpenXR-MixedReality#116]
When playing Iracing through openXR (mixed reality) the game flashes constantly in red in both eyes, makes its unplayable.
Not sure where and how to report this properly. Could be drivers issue? Or iracing implementation? Or openxr compatibility issue with new AMD cards?

Video: https://youtu.be/yoAwpAsAQ-4

**Comment by indus3a** [comment]
Issue found: ingame built in antialiasing creates red artefacts. Only with openxr & new amd card.

**Comment by mbucchia-msft** [comment]
Closing as 3rd party driver issue.
