### ISSUE TITLE
Why is the runtime not using the holographic remoting extensions？

### ISSUE THREAD

**Issue by amao6666** [microsoft/OpenXR-MixedReality#118]
Wish to use the following extensions:

“XR_MSFT_holographic_remoting”
“XR_MSFT_holographic_remoting_frame_mirroring”
“XR_MSFT_holographic_remoting_speech”

**Comment by mbucchia-msft** [comment]
Hi, you can find instructions on Microsoft Remoting for HoloLens 2 here: https://learn.microsoft.com/en-us/windows/mixed-reality/develop/native/holographic-remoting-create-remote-openxr

Remoting isn't part of the OpenXR for WMR runtime, instead it is its own OpenXR runtime, that implements the extensions you listed. The page above explains how to obtain that runtime and how to activate and use the extensions.
