### ISSUE TITLE
113.2304.14003 Results in terrible image warping in DCS

### ISSUE THREAD

**Issue by bendean1987** [microsoft/OpenXR-MixedReality#120]
Hey,

For the last week I've been trying to track down a new issue in DCS of clouds/scenery flickering and warping around massively in low light conditions. Making DCS unplayable for me. I've tried everything I could think of, including rolling back the version of DCS, to no help. 

It turned out the issue was caused by the updated to 113.2304.14003.

I'm unsure exactly what new feature is causing this issue. But its definitely related to motion reprojection. Perhaps the new motion vector reprojection?

Whatever has changed has made the motion reprojection **extremely unpleasant** in DCS, specially when flying at night. It has also made my FPS much more unstable, with regular FPS dips for no reason. I unticked the "Use Latest Preview Runtime" in the OpenXR setttings and rolled back to 112.2211.2002, which has restored my previous performance and motion reprojection behavior.

Please consider adding toggle switches to allow us to enable or disable new reprojection techniques from within the OpenXR toolkit.

Thanks
Ben

12900KF - 64GB DDR5 - RTX 3090 - Reverb G2

**Comment by ghost** [comment]
> Please consider adding toggle switches to allow us to enable or disable new reprojection techniques from within the OpenXR toolkit.

Done in the latest runtime preview build.
