### ISSUE TITLE
XR Error Path Unsupported w/ Pimax Crystal

### ISSUE THREAD

**Issue by iam7foot1** [microsoft/OpenXR-MixedReality#121]
Using Pimax Crystal and keep getting the following error upon app startup. 

xrSuggestInteractionProfileBindings failed with XR_ERROR_PATH_UNSUPPORTED

Controllers are paired and running, and no other SteamVR apps running simultaneously. I swear I've tried everything and can't find any other discussions with this error. Any suggestions? Thank you in advance.

**Comment by mbucchia** [comment]
This isn't a fatal error. Certain runtimes don't support all interaction profiles. This message you are seeing is benign.

Also, you are on the wrong GitHub, this is the one you are looking for: https://github.com/mbucchia/Pimax-OpenXR
