### ISSUE TITLE
Image files in samples/BasicXrApp/Assets/ broken, prevent build

### ISSUE THREAD

**Issue by max-krichenbauer** [microsoft/OpenXR-MixedReality#49]
Hello!

The PNG image files in `samples/BasicXrApp/Assets/` are corrupted which prevents building the BasicXrApp.

```
1>Package.appxmanifest(36,9): error APPX1618: App manifest references the square 150x150 logo image 'Assets\Square150x150Logo.scale-200.png' which is not a valid image file.
1>Package.appxmanifest(40,26): error APPX1618: App manifest references the wide 310x150 logo image 'Assets\Wide310x150Logo.scale-200.png' which is not a valid image file.
1>Package.appxmanifest(37,9): error APPX1618: App manifest references the small logo image 'Assets\Square44x44Logo.scale-200.png' which is not a valid image file.
1>Package.appxmanifest(37,9): error APPX1618: App manifest references the small logo image 'Assets\Square44x44Logo.targetsize-24_altform-unplated.png' which is not a valid image file.
1>Package.appxmanifest(19,6): error APPX1618: App manifest references the store logo image 'Assets\StoreLogo.png' which is not a valid image file.
1>Package.appxmanifest(41,27): error APPX1618: App manifest references the splash screen image 'Assets\SplashScreen.scale-200.png' which is not a valid image file.
```

These "image files" are actually text files with contents like:
```
version https://git-lfs.github.com/spec/v1
oid sha256:a41a053b3fc3b0c109720ccd437a19725ae9163ea75990222a12b596b9c7ca76
size 1430
```

Best regards,
Max

**Comment by max-krichenbauer** [comment]
Found the problem:
this seems to be a bug with GitHub itself - when downloading the repository as a zip archive (instead of cloning), the image files in the zip archive are broken.
I got confused when checking the files in the repository in the web browser, because the images actually look like what could be a "broken image" placeholder.

So the solution is to download the files manually separately from the archive.

**Comment by gongminmin** [comment]
That's because this project is with lfs enabled. When cloning the project with git, you need to have git-lfs (https://git-lfs.github.com/) installed, and put lfs argument in the command line to enable the feature. Images are stored as large file, that's why they are presented to be text files when lfs is not enabled.

**Comment by brycehutchings** [comment]
We've made a change to remove usage of Git LFS, so you should be able to clone it successfully if you try again.

**Comment by SoylentGraham** [comment]
The zip is still broken, should removing use of LFS have fixed this?
