### ISSUE TITLE
Some XrHandles can't be readily used in additional dlls that don't consume the openxr loader

### ISSUE THREAD

**Issue by chrisfromwork** [microsoft/OpenXR-MixedReality#78]
class definitions for items like SpaceHandle use xr* functions that requiring linking against the loader lib. It would be great if these classes could be defined in a manner where xrGetInstanceProcAddr/function pointers can be used, so that these helper handles can be used in dlls that don't link against the loader lib/setup the openxr experience.

This isn't a blocking issue, folks can unblock themselves by using UniqueExtHandles + manually providing the destroy function obtained through xrGetInstanceProcAddr.

**Comment by yl-msft** [comment]
Great feedback!  The workaround of using UnqiueExtHandles is the right way to do this.  Would be nice if the library can do this automatically.
