### ISSUE TITLE
Controller model extension with Reverb G2 controllers

### ISSUE THREAD

**Issue by pk15950** [microsoft/OpenXR-MixedReality#89]
Has the `XR_MSFT_controller_model` extension been tested with the HP Reverb G2 controllers? If so, is the glTF model returned by the Windows Mixed Reality runtime different than the model for the standard WMR controllers? 

Thanks for the great samples!

**Comment by brycehutchings** [comment]
Yes, each of the three kinds of WMR controllers have matching models.

**Comment by pk15950** [comment]
Ok, thank you!
