### ISSUE TITLE
Compatibility Issue with UnityEngine.Windows.Speech namespace ?

### ISSUE THREAD

**Issue by jasonhbartlett** [microsoft/OpenXR-MixedReality#95]
Hello, I'm posting this in a few places as I'm not sure exactly who is the culprit for this issue.

I'm making a VR training app and the target platform is Standalone>Windows.  I'm using Unity 2020.3 and OpenXR.  See below for specific versions.

I have a script that uses the UnityEngine.Windows.Speech namespace that lets me subscribe to the PhraseRecognizedDelegate OnPhraseRecognized event.  ( this API is part of the UnityEngine.CoreModule.dll )

My Issue: Everything works great EXCEPT when I have WMR headset connected and the WMR Portal running with Mixed Reality OpenXR runtime.

I have tested that my voice commands DO work fine when running in editor (without WMR headset attached), as a built .exe (again without WMR headset attached), AND even works with Oculus Quest (via Link and the Oculus OpenXR runtime.)

My voice commands DO NOT work with either HP Reverb G1 or G2 and running the WMR portal and the Mixed Reality OpenXR runtime.

I have verified that the microphone device is working as I created a simple echo script that plays what the microphone hears back to me.

As another data point I have an older VR project that I built with Unity 2019.4 with the same target but that uses the Windows Mixed Reality plugin (not OpenXR).  The voice commands DO work fine in that app.

So this kinda points me to some problem with the Mixed Reality OpenXR runtime as being compatible with the UnityEngine.CoreModule.dll and specifically with the UnityEngine.Windows.Speech namespace.

Any help with this would be appreciated. Thank you!

SW Versions:
Windows 11 Pro
Unity 2020.3.16
WMR Runtime 107.2109.10010
Packages Include:
XR Plugin Management 4.07
XR Interaction Toolkit 1.0.0-pre.5
OpenXR Plugin 1.2.8
Microsoft Plugins:
Mixed Reality OpenXR Plugin 1.0.2
Mixed Reality Input 0.9.2006
Microsoft Spatializer 1.0.196

**Comment by jasonhbartlett** [comment]
I have also opened an issue on the github page for OpenXR-Unity-MixedReality-Samples here: [Issue47](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/issues/47)
This issue is reproducible without the MS Plugins mentioned above so seems to be related to something like Unity or Microsoft or MS OpenXR runtime.  I can close this issue and track it over there if you prefer.
Or, also I would be curious to know if anyone else over here has a take on it.

**Comment by yl-msft** [comment]
Thanks for the report.  Since this issue is a Unity specific issue, let's track it with  Issue47 on Unity sample repo.  Closing this as duplication.
